services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./Backend/uploads:/app/uploads
